version: "3.7"
services:
  umfrontend:
    build:
      context: ../user-management-frontend
      dockerfile: Dockerfile
    depends_on:
      - umbackend
    ports:
      - 3000:3000
    restart: always
  umbackend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresdb
    environment:
      - POSTGRES_HOST=postgresdb
    ports:
      - 3001:3001
    restart: always
  postgresdb:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    restart: always

